Kernel 5.10
adjust/gentoo-overlay pull request #506
Opened 2020-12-17 17:48 UTC by patricklauer

plus eapi7
plus slot per major kernel version, which should simplify updates

2020-12-18 10:35 UTC, monsieurp requested changes
Final comment: the commit message should be `$CAT/$PN` but you know that already :)

2020-12-18 10:35 UTC, monsieurp commented on sys-kernel/buildkernel/buildkernel-5.10.1.ebuild
> +	mkdir -p "$S"
`|| die`

2020-12-18 10:35 UTC, monsieurp commented on sys-kernel/buildkernel/buildkernel-5.10.1.ebuild
> +	mkdir -p "$S/tmp/kernel"
Ditto for this line and the 2 lines below.

2020-12-18 10:35 UTC, monsieurp commented on sys-kernel/buildkernel/buildkernel-5.10.1.ebuild
> +	echo "Building kernel ..."
`einfo` ?

2020-12-18 10:35 UTC, monsieurp commented on sys-kernel/buildkernel/buildkernel-5.10.1.ebuild
> +	rm -rf "$S/final/lib/firmware" || die
`rm` always return 0 with the `-f` option. Consider removing it.

2020-12-18 10:35 UTC, monsieurp commented on sys-kernel/buildkernel/buildkernel-5.10.1.ebuild
> +	mkdir -p "${D}/usr/share"
`|| die`

2020-12-18 10:35 UTC, monsieurp commented on sys-kernel/buildkernel/buildkernel-5.9.15.ebuild
> +# Copyright 1999-2020 Gentoo Authors
Same comments apply for this ebuild.

2020-12-18 10:35 UTC, monsieurp commented on sys-kernel/gentoo-kernel/gentoo-kernel-5.10.1.ebuild
> +	cp -var "${WORKDIR}"/* "${D}"
add `|| die` here and to all commands below.

2020-12-18 10:35 UTC, monsieurp commented on sys-kernel/gentoo-kernel/gentoo-kernel-5.10.1.ebuild
> +		cd /usr/src/linux-${PV}-gentoo/ && make -s modules_prepare
Break it down into two seperate commands and also add `|| die`.

2020-12-18 10:35 UTC, monsieurp commented on sys-kernel/buildkernel/buildkernel-5.10.1.ebuild
> +	cp "$S/tmp/kernel/Module.symvers" "$S/final/Module.symvers"
`|| die`

2021-01-17 18:22 UTC, patricklauer commented on sys-kernel/buildkernel/buildkernel-5.10.1.ebuild
> +	mkdir -p "$S"
Can't fail, so why care ;)

2021-01-17 18:28 UTC, merged