Change running user/group to root
adjust/gentoo-overlay pull request #507
Opened 2021-01-06 16:12 UTC by blueSherii

Issue related https://github.com/adjust/infrastructure/issues/10890

2021-01-07 13:21 UTC, blueSherii commented on dev-db/aerospike-server-enterprise/files/aerospike.init3
> +
user and group removed from this section .
A new init file created to preserve the old ones

2021-01-07 14:22 UTC, einhverfr requested changes
So let's sync up on this.

My thinking is the conf.d system is probably a better place for this rather than the gentoo overlay files directly and then we can create those with our automation.  Let's discuss soon

2021-01-07 14:22 UTC, einhverfr commented on dev-db/aerospike-server-enterprise/files/aerospike.init3
> +
not sure why this is needed.  Couldn't putting relevant things in conf.d by our automation do it better?

2021-01-07 14:27 UTC, monsieurp requested changes

2021-01-07 14:27 UTC, monsieurp commented on dev-db/aerospike-server-enterprise/aerospike-server-enterprise-4.5.0.12.ebuild
> +	insinto /etc/conf.d
Please use the `newconfd` function instead:
> newconfd | Install an /etc/conf.d entry using the second argument as the name

See: https://devmanual.gentoo.org/function-reference/install-functions/

2021-01-07 16:01 UTC, blueSherii commented
@einhverfr I think putting this in gentoo-overlay is better when the conf.d file is mostly static and not "server/flavour/other config" dependent

2021-01-08 08:21 UTC, mcharriere commented
from my point of view, there is no need for this PR. The issue can be solved adding a conf.d in the infra repo. If fact since this changes the default values of user/root it will also change where root is not needed (like in aero-tracker).

2021-01-08 15:44 UTC, closed without merging