dev-db/parquet_fdw: initial parquet_fdw ebuild
adjust/gentoo-overlay pull request #529
Opened 2021-02-03 21:19 UTC by xmhd

Initial stab at packaging parquet_fdw.

Part of WIP for [https://github.com/adjust/infrastructure/issues/10897](url)

Ebuild is currently version 9999 and thus pulls from git as parquet_fdw repo hasn't had a tag or release for quite some time. This can be set to a specific commit/date if required.

Ebuild has been tested locally on a ~amd64 Gentoo Linux system. I can confirm it builds successfully.

TODO:
- Which versions of postgres is parquet_fdw compatible with?
- Non live (9999) ebuild for future release(s)
- Testing

2021-02-05 08:16 UTC, monsieurp requested changes

2021-02-05 08:16 UTC, monsieurp commented on dev-db/parquet_fdw/metadata.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Copy and paste an metadata.xml file from another package in the repo.

2021-02-05 08:16 UTC, monsieurp commented on dev-db/parquet_fdw/parquet_fdw-9999.ebuild
> +KEYWORDS=""
amd64 at least I guess?

2021-02-05 08:16 UTC, monsieurp commented on dev-db/parquet_fdw/parquet_fdw-9999.ebuild
> +if [[ ${PV} == 9999 ]]; then
Although I'm not against 9999 ebuilds, we should ask the repository owner to make a release. https://github.com/adjust/parquet_fdw is managed by @zilder I believe.

2021-02-05 08:20 UTC, monsieurp commented
Hey @zilder what's up? Could you please make a release of parquet_fdw? There's been several changes since the last one (https://github.com/adjust/parquet_fdw/tags). We need to package it for a project and having an up-to-date release would help us tremendously. Thank you!

2021-02-05 09:47 UTC, zilder commented
Hi,
sure, here is the new release:
https://github.com/adjust/parquet_fdw/releases/tag/v0.2

Though i'm going to release a new version with major refactoring and couple of new features requested by AB team in couple of weeks.

2021-02-05 09:48 UTC, monsieurp commented
awesome thanks @zilder :)

2021-02-05 09:59 UTC, zilder commented on dev-db/parquet_fdw/parquet_fdw-9999.ebuild
> +LICENSE="POSTGRESQL GPL-2"
`parquet_fdw` is licensed under postgresql license which is bsd-like. So i think GPL isn't correct here.

2021-02-05 10:01 UTC, zilder commented on dev-db/parquet_fdw/parquet_fdw-9999.ebuild
> +POSTGRES_COMPAT=( 11 12 )
I test it on 10, 11, 12 and 13

2021-02-08 13:15 UTC, xmhd commented
@monsieurp  @zilder 

Thank you both for feedback / information. I have updated the ebuild accordingly.

2021-02-08 15:17 UTC, monsieurp approved these changes

2021-02-09 13:50 UTC, merged