bagger: bump version to 0.4
adjust/gentoo-overlay pull request #531
Opened 2021-02-05 20:49 UTC by artemyevav

Bagger 0.4 was released recently, this is the repo update to use new bagger binary.

2021-02-17 09:27 UTC, monsieurp requested changes

2021-02-17 09:27 UTC, monsieurp commented on app-admin/bagger-tools/bagger-tools-0.4.ebuild
> +EAPI=5
```suggestion
EAPI=7
```

2021-02-17 09:27 UTC, monsieurp commented on app-admin/bagger-tools/bagger-tools-0.4.ebuild
> +	KEYWORDS="~amd64"
```suggestion
      KEYWORDS="amd64"
```
Our software releases don't need to be keyworded I think. ;)

2021-02-17 09:27 UTC, monsieurp commented on app-admin/bagger-tools/files/schaufel_listener-0.4.initd
> +	LISTENER_OPTS+=" -j ${LISTENER_JOBS}"
This entire piece of code can be moved to the conf.d file. Please move it and I'll make some suggestions to improve it then.

2021-02-17 09:27 UTC, monsieurp commented on app-admin/bagger-tools/files/schaufel_listener-0.4.initd
> +	--stderr ${LISTENER_LOG_FILE}"
```suggestion
start_stop_daemon_args="--verbose --user ${LISTENER_USER} --group ${LISTENER_GROUP}"
command_background="true"
directory="${LISTENER_DIR}"
output_log="${LISTENER_LOG_FILE}"
error_log="${LISTENER_LOG_FILE}"

2021-02-17 09:40 UTC, artemyevav commented
All these changes look like a `quality of life`. That's out of a scope of this PR, the only thing I need is bumping a version to be able to install 0.4.

2021-02-17 09:50 UTC, monsieurp commented
Why are you asking for my review then? :thinking: If the ebuild works and is installable, commit it straight to master and call it a day in this case.

2021-02-17 09:52 UTC, monsieurp approved these changes

2021-02-17 10:02 UTC, merged

2021-02-23 19:15 UTC, einhverfr commented on app-admin/bagger-tools/bagger-tools-0.4.ebuild
> +	KEYWORDS="~amd64"
I think we are keywording btw.  We might want to rethink our policies there though.  I will leave that up to you and David