PostgresTools-0.1: add
adjust/gentoo-overlay pull request #535
Opened 2021-02-24 15:02 UTC by varilci

Bumped PostgresTools to v0.1 for easier overla management. Also
updated the euild to EAPI7.

2021-02-24 20:51 UTC, xmhd requested changes
```
# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
```

2021-02-24 20:51 UTC, xmhd commented on dev-perl/PostgresTools/PostgresTools-0.1.ebuild
> +# Distributed under the terms of the GNU General Public License v2
Copyright should be 1999 - $current_year Gentoo Authors

2021-02-24 20:51 UTC, xmhd commented on dev-perl/PostgresTools/PostgresTools-0.1.ebuild
> +fi
I know it's an argument of posix vs bash, but given that we're using Gentoo and the posix compliant ebuilds argument died (sadly) with Roy Marples a decade ago, I would do like so:

```
if [[ ${PV} == 9999* ]] ; then
    EGIT_REPO_URI="https://github.com/adjust/postgres_tools.git"
else
    SRC_URI="https://github.com/adjust/postgres_tools/archive/v${PVR}.tar.gz"
fi
```

I seem to recall there being something in the Gentoo dev handbook re: [ .. ] vs [[ .. ]] as a result of Roy Marples fighting for ebuilds to be posix compliant, but I can't seem to find it right now. Every ebuild example in the handbook I can find uses the bash equivalent though fwiw.

Use of ${HOMEPAGE} and ${PN} in SRC_URI is discouraged, see [https://devmanual.gentoo.org/ebuild-writing/variables/#use-of-constant-value-variables-in-ebuilds](url)

2021-02-24 20:51 UTC, xmhd commented on dev-perl/PostgresTools/PostgresTools-0.1.ebuild
> +KEYWORDS="~amd64"
add LICENSE="MIT" in this section

2021-02-25 10:20 UTC, varilci commented on dev-perl/PostgresTools/PostgresTools-0.1.ebuild
> +# Distributed under the terms of the GNU General Public License v2
I was using app-vim/gentoo-syntax :sweat_smile: will fix to align with other ebuilds

2021-02-25 10:30 UTC, varilci commented on dev-perl/PostgresTools/PostgresTools-0.1.ebuild
> +fi
Believe it or not, I was actually looking at some other ebuilds in the repository, and writing like this seemed intuitive to me (e.g if there will be a minor change in homepage, it won't be affected too much). But since I see it's discouraged by Gentoo, I'll follow it :slightly_smiling_face:

2021-02-25 19:40 UTC, xmhd approved these changes
lgtm

2021-02-25 19:40 UTC, merged