sys-cluster/k3s: initial import
adjust/gentoo-overlay pull request #569
Opened 2021-04-16 13:43 UTC by xmhd

import a slightly outdated sys-cluster/k3s from quark-overlay and improve/version bump where necessary.

2021-04-16 16:24 UTC, varilci reviewed
It gets complied and installed on a fresh environment successfully. May want to test it's capabilities later by running it with some test stuff though.

2021-04-18 03:26 UTC, T-10810 approved these changes
overlay

>

2021-04-18 03:28 UTC, T-10810 approved these changes

2021-04-20 08:54 UTC, monsieurp requested changes
Those changes can be addressed in a subsequent PR.

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/files/k3s.openrc
> +#!/sbin/openrc-run
This entire file gives me nightmares. Please don't merge it as-is.

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/files/k3s.openrc
> +command_args="${CMD_K3S} ${K3S_OPTIONS} >>${LOG_FILE} 2>&1"
Why `>>${LOG_FILE}` if `output_log` and `error_log` are set?

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/files/k3s.openrc
> +[ "${CMD_K3S}" = "server" ] || SYSTEM_NAME=k3s-${CMD_K3S}
Ditto.

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/files/k3s.openrc
> +    rm -f /tmp/k3s.*
Why?

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/files/k3s.openrc
> +if [ -f /etc/conf.d/k3s ]; then source /etc/conf.d/k3s; fi
No. OpenRC does it already.

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/files/k3s.openrc
> +set -o allexport
Why?

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/k3s-0.9.1.ebuild
> +	sed -i -e 's|go generate|go run pkg/codegen/main.go|' scripts/package-cli
`|| die`

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/k3s-0.9.1.ebuild
> +#!/bin/bash
`#!/usr/bin/env bash`

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/k3s-0.9.1.ebuild
> +	>=dev-lang/go-1.12
This version of go doesn't exist anymore in the Portage tree, `dev-lang/go` suffices.

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/k3s-0.9.1.ebuild
> +inherit eutils golang-build golang-vcs-snapshot
Not sure what the `eutils` is inherited for here.

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/k3s-0.9.1.ebuild
> +	mkdir -p build/static/charts
`|| die`

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/k3s-0.9.1.ebuild
> +	./scripts/package-cli
missing `|| die` to both commands.

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/files/k3s.openrc
> +SYSTEM_NAME=k3s
This should be set in the conf.d file.

2021-04-20 08:54 UTC, monsieurp commented on sys-cluster/k3s/files/k3s.openrc
> +LOG_FILE=/var/log/${SYSTEM_NAME}.log
Also belongs in the conf.d file.

2021-04-24 15:17 UTC, xmhd commented
closing this as the package has just entered ::gentoo and is being maintained there.

2021-04-24 15:17 UTC, closed without merging