dev-python/{fastapi,starlette}: initial import
adjust/gentoo-overlay pull request #587
Opened 2021-05-05 13:33 UTC by xmhd

fastapi ebuild by me
starlette from guru overlay

2021-05-05 13:51 UTC, xmhd commented
todo:

add missing dependencies from starlette (seems to be quite a few)

or

disable 'web stuff' (straight from the source @ pypi) to remove the dependency on starlette.

2021-05-12 04:02 UTC, oziey88 commented
ref: https://github.com/adjust/infrastructure/issues/10126

2021-05-19 01:43 UTC, xmhd commented
ok, I've added all ebuilds required for this:

dev-python/fastapi - by me

remainder pulled from guru overlay (had to tweak most of them slightly).

my initial thoughts are that if we remove USE="test" for starlette, then we can probably remove _most_ of these packages, and leave ourselves with fewer packages to maintain.... especially seeing as I don't believe we will ever use testing for fastapi or starlette.

thoughts?

@varilci @monsieurp @oziey88 @nesat

2021-05-20 10:29 UTC, varilci commented
I am all for "less packages to maintain".

2021-05-20 11:48 UTC, nesat commented
In FastAPI's documents it says FastAPI is based on and subclass of Starlette:

> FastAPI is fully compatible with (and **based on**) **Starlette**. So, any additional Starlette code you have, will also work.
> 
> FastAPI is actually a **sub-class of Starlette**. So, if you already know or use Starlette, most of the functionality will work the same way.

https://fastapi.tiangolo.com/features/#starlette-features

Starlette is also one of the 2 core dependencies of FastAPI:
https://github.com/tiangolo/fastapi/blob/aece74982d7c9c1acac98e2c872c4cb885677fc7/pyproject.toml#L35


If I am missing something and the only affected feature would be `TestClient`, then we are fine with removing Starlette. I just want to be sure that we won't have any unexpected error if we use FastAPI without Starlette

2021-05-21 17:16 UTC, alip approved these changes
I have built the new python modules added with this pr on an x86_64 Gentoo ~amd64 system with FEATURES=test, python targets set to 3.{7..9} and without the doc USE flag. Tests and builds successfully.
Reviewed the ebuilds. I could not pinpoint any important issues. I made some recommendations here and there for potential improvements. See the review.

Random observations that are not directly related to this PR:
- dev-python/pytest-mock-3.5.1::gentoo fails tests with python3_7
- dev-python/python-email-validator-1.1.2::gentoo fails tests with python3_{7,9}
- dev-python/pydantic-1.8.1::gentoo fails tests with python3_9

2021-05-24 14:08 UTC, xmhd commented on dev-python/aiosqlite/aiosqlite-0.17.0.ebuild
> +RESTRICT="!test? ( test )"
that logic == if USE="-test" then RESTRICT="test"

2021-05-24 14:25 UTC, xmhd commented on dev-python/sphinxcontrib-napoleon/sphinxcontrib-napoleon-0.7.ebuild
> +LICENSE="BSD"
agree++

2021-05-24 14:25 UTC, xmhd commented on dev-python/starlette/starlette-0.14.2.ebuild
> +	optfeature "Server Sent Events" dev-python/sse-starlette
agree++ these really should be in DEPEND/RDEPEND as their own thing, rather than if USE=test and outputting optfeature nonsense.

2021-05-24 14:26 UTC, xmhd commented on dev-python/pytest-benchmark/pytest-benchmark-3.2.3.ebuild
> +	pytest -vv || die "Tests fail with ${EPYTHON}"
agree++

2021-05-24 14:26 UTC, xmhd commented on dev-python/graphql-relay/graphql-relay-3.0.0.ebuild
> +		dev-python/pytest-asyncio[${PYTHON_USEDEP}]
I have no idea, these ebuilds are pulled from the guru overlay. I didn't modify them much/at all before opening this PR for us to decide what needs changed.

2021-05-24 14:27 UTC, xmhd commented on dev-python/graphene/graphene-3.0.0_beta7.ebuild
> +MYP="${PN}-${MYPV}"
agree++

2021-05-24 14:27 UTC, xmhd commented on dev-python/hunter/hunter-3.3.3.ebuild
> +		"${EPYTHON}" tests/setup.py build_ext --force --inplace || die
agree++

2021-05-24 14:27 UTC, xmhd commented on dev-python/hunter/files/remove-setuptools_scm-upper-constraint.patch
> ++++ b/setup.py
agree++

2021-05-24 14:31 UTC, xmhd commented
@alip wdyt about removing USE='"test" on these packages and trimming fat wrt the number of packages we will have to maintain?

2021-05-24 19:06 UTC, nesat commented
@xmhd I have just realised that I misunderstood your question previously. From my perspective, we can remove `starlette` test dependencies but there are some optional `fast-api` dependencies we may still need e.g. `requests`, `python-multipart`: https://github.com/tiangolo/fastapi/blob/aece74982d7c9c1acac98e2c872c4cb885677fc7/pyproject.toml#L84-L96 

Those optional `fast-api` dependencies are also optional for `starlette`: https://github.com/encode/starlette/blob/d26f44b4aeaec63ae8ce0a4f34dea7439da48012/requirements.txt#L2-L8
However, in the `starlette` ebuild file they appear as test dependencies. Is there anything I am missing? 

What about running https://github.com/adjust/benchmarktool-api to make sure which optional dependencies are required for the project and which not? If there are some optional dependencies required in other projects in the future, they can be requested to be included later maybe?

2021-05-25 08:04 UTC, alip commented
> @alip wdyt about removing USE='"test" on these packages and trimming fat wrt the number of packages we will have to maintain?

I have no particular problems with that. I'd still keep them in a branch (or maybe our own custom package sets in the future?) in case we want to verify e.g: python-3.9 support works as expected when that python version hits stable. I'm in favour of running tests on the binhost in general as much as we can but the vast number of dependencies in this case makes an alternative approach logical.

2021-05-25 08:08 UTC, xmhd commented
> > @alip wdyt about removing USE='"test" on these packages and trimming fat wrt the number of packages we will have to maintain?
> 
> I have no particular problems with that. I'd still keep them in a branch (or maybe our own custom package sets in the future?) in case we want to verify e.g: python-3.9 support works as expected when that python version hits stable. I'm in favour of running tests on the binhost in general as much as we can but the vast number of dependencies in this case makes an alternative approach logical.

this wfm, running with USE=test would certainly be ideal.

2021-05-25 14:54 UTC, monsieurp commented on dev-python/fastapi/fastapi-0.63.0.ebuild
> +PYTHON_COMPAT=( python3_{7,8,9} )
Some syntax sugar:
```suggestion
PYTHON_COMPAT=( python3_{7...9} )
```

2021-05-25 15:03 UTC, monsieurp requested changes

2021-06-10 10:45 UTC, nesat commented
New ref: https://github.com/adjust/infrastructure/issues/12624

2021-06-10 18:16 UTC, merged