dev-util/sonarqube-developer
adjust/gentoo-overlay pull request #730
Opened 2022-05-09 01:55 UTC by licebmi

Sonarqube developer server package.

2022-05-16 08:19 UTC, LehningerAdjust commented
@monsieurp Please review.

2022-05-16 08:23 UTC, monsieurp commented
CI is broken unfortunately so please ignore for now.

2022-05-16 08:25 UTC, monsieurp requested changes

2022-05-16 08:25 UTC, monsieurp commented on dev-util/sonarqube-developer/files/exit-codes.patch
> ++	exit 1
Missing space here:
```suggestion
         exit 1
```

2022-05-16 08:25 UTC, monsieurp commented on dev-util/sonarqube-developer/sonarqube-developer-8.9.8.54436.ebuild
> +	mv sonarqube-${PV} ${P}
```suggestion
        mv sonarqube-${PV} ${P} || die
```

2022-05-16 09:02 UTC, licebmi commented on dev-util/sonarqube-developer/sonarqube-developer-8.9.8.54436.ebuild
> +	mv sonarqube-${PV} ${P}
Is this required?
I mean the zipfile is verified with checksum by portage, and mv is an atomic operation which just migrates an inode. Plus the next step will fail if ${P} doesn't exists.

2022-05-25 09:24 UTC, monsieurp approved these changes

2022-05-25 09:25 UTC, monsieurp commented on dev-util/sonarqube-developer/sonarqube-developer-8.9.8.54436.ebuild
> +	mv sonarqube-${PV} ${P}
Hey! Yes it's better to add `|| die` statements to make sure the file is indeed renamed.

2022-06-10 09:28 UTC, merged