files/vmagent.{confd,initd}: create generic init files for vmagent
adjust/gentoo-overlay pull request #770
Opened 2022-09-19 16:39 UTC by zegeek

To expand the victoriametrics cluster and in order to allow vm to scrape metrics exports à la Prometheus, we need to deploy vmagents that will scrape the /metrics endpoints and write to victoriametrics. 
This PR adds the init/conf file of a generic vmagent, that we will provision using TRex/cmdb.

2022-09-20 07:57 UTC, monsieurp requested changes

2022-09-20 07:57 UTC, monsieurp commented on dev-db/victoria-metrics/files/vmagent.initd
> +command_args="-httpListenAddr=${httpListenAddr} -envflag.enable -envflag.prefix=${RC_SVCNAME}_"
`-envflag.prefix=${RC_SVCNAME}_"`
there's an extra `_` here is it normal?

2022-09-20 07:57 UTC, monsieurp commented on dev-db/victoria-metrics/files/vmagent.initd
> +    checkpath -f -m 0440 -o "${command_user}" ${!config_file}
indentation

2022-09-20 07:57 UTC, monsieurp commented on dev-db/victoria-metrics/files/vmagent.initd
> +export ${RC_SVCNAME}_remoteWrite_maxDiskUsagePerURL="${MAX_DISK_USAGE:-200GB}"
a couple of questions here:
* why do you export those variables?
* you should set a default value in the confd file instead of using the `${FOOBAR:-value}` pattern, it makes more sense IMHO

2022-09-20 07:58 UTC, zegeek commented on dev-db/victoria-metrics/files/vmagent.initd
> +command_args="-httpListenAddr=${httpListenAddr} -envflag.enable -envflag.prefix=${RC_SVCNAME}_"
yes, because the environment variables will end up having the name of the service as a prefix, like  `vmagent_1_<something_here>`

2022-09-20 08:04 UTC, zegeek commented on dev-db/victoria-metrics/files/vmagent.initd
> +export ${RC_SVCNAME}_remoteWrite_maxDiskUsagePerURL="${MAX_DISK_USAGE:-200GB}"
- exposing the variables is how we configure victoriametrics components, either by cmdline flags, or by having these env variables and passing the `-envflag.enable` option to the daemon. Taken from vmagent documentation:
```
 -envflag.enable
     Whether to enable reading flags from environment variables additionally to command line. Command line flag values have priority over values from environment vars. Flags are read only from command line if this flag isn't set
```
- based on other init scripts, usually the defaults are defined in the init script for example: 
https://github.com/adjust/gentoo-overlay/blob/bb63964cc1fbfd3f8c280403ac7e5e864f7f7daf/app-admin/schaufel/files/schaufel.initd#L3-L8
or 
https://github.com/adjust/gentoo-overlay/blob/bb63964cc1fbfd3f8c280403ac7e5e864f7f7daf/app-admin/filebeat/files/filebeat.initd#L5-L10

2022-09-21 09:11 UTC, monsieurp requested changes

2022-09-21 09:11 UTC, monsieurp commented on dev-db/victoria-metrics/files/vmagent.initd
> +export ${RC_SVCNAME}_remoteWrite_maxDiskUsagePerURL="${MAX_DISK_USAGE:-200GB}"
Upon starting a service, OpenRC will source its conf.d file first and pick up values from there. That's why I think setting defaults values in the init script is wrong and actually redundant.

I understand but it's not the right way to do it and we should definitely fix the schaufel ebuilds as well. See the mesos conf.d/init.d files here: https://github.com/adjust/gentoo-overlay/tree/master/sys-cluster/mesos/files

2022-09-21 09:46 UTC, monsieurp approved these changes

2022-09-21 09:47 UTC, merged