aerospike-prometheus-exporter: fix ebuild and init script
adjust/gentoo-overlay pull request #771
Opened 2022-09-19 17:29 UTC by zegeek

Ebuild had some issues that didn't allow proper installation + missing ownership of certain directories change. 
Init script had a minor issues that prevented from starting the daemon.
related to adjust/infrastructure#17556

2022-09-20 07:59 UTC, monsieurp requested changes

2022-09-20 07:59 UTC, monsieurp commented on app-metrics/aerospike-prometheus-exporter/files/aerospike-prometheus-exporter.initd
> +	#fi
pls get rid of those lines, we can still look into the repo's history if we need this code block again

2022-09-20 08:28 UTC, zegeek commented on app-metrics/aerospike-prometheus-exporter/files/aerospike-prometheus-exporter.initd
> +	#fi
yeah that makes sense

2022-09-21 09:05 UTC, monsieurp approved these changes

2022-09-21 09:20 UTC, merged