net-misc/loki-promtail-bin add ebuild
adjust/gentoo-overlay pull request #868
Opened 2024-03-19 08:31 UTC by ibra-adjust

Add an ebuild for net-misc/loki-promtail-bin

2024-03-19 08:58 UTC, sibuthomasmathew commented on net-misc/loki-promtail-bin/files/promtail.yml
The configuration file must be kept independent of the build

2024-03-19 09:13 UTC, ibra-adjust commented on net-misc/loki-promtail-bin/files/promtail.yml
Could you please explain why it must be kept independent of the build ?

2024-03-19 11:03 UTC, sibuthomasmathew requested changes

2024-03-19 11:03 UTC, sibuthomasmathew commented on net-misc/loki-promtail-bin/files/promtail.yml
A lot of the configuration like file `positions` or `client.url` can change. So, we need to flexibility to change it dynamically using ansible or other options.

2024-03-19 11:03 UTC, sibuthomasmathew commented on net-misc/loki-promtail-bin/files/promtail.yml
> +  - url: 'http://localhost:3100/loki/api/v1/push'
Is this a dummy value?

2024-03-19 11:03 UTC, sibuthomasmathew commented on net-misc/loki-promtail-bin/files/promtail.yml
> +          __path__: /var/log/*log
Do we want promtail reading all the log files?

2024-03-19 11:05 UTC, sibuthomasmathew commented on net-misc/loki-promtail-bin/files/promtail.yml
> +  grpc_listen_port: 0
We don't need promtail running as a server. Let's disable it
```suggestion
 disable: true
```

2024-03-26 12:02 UTC, ibra-adjust commented on net-misc/loki-promtail-bin/files/promtail.yml
OK, I will remove the configuration file.

2024-03-26 13:23 UTC, sibuthomasmathew approved these changes

2024-07-05 09:11 UTC, closed without merging